Update ansible for trixie and the sb-upgrade tool to download nhl_setup

diff --git a/nhl-image/ansible/files/sb_image/sbtools/sb-upgrade b/nhl-image/ansible/files/sb_image/sbtools/sb-upgrade
--- a/nhl-image/ansible/files/sb_image/sbtools/sb-upgrade
+++ b/nhl-image/ansible/files/sb_image/sbtools/sb-upgrade
@@ -2,10 +2,17 @@
 # Borrowed from oh-my-zsh
 # https://github.com/ohmyzsh/ohmyzsh/blob/master/tools/upgrade.sh
 
+ARCH=$(uname -m)
 cd /home/pi/nhl-led-scoreboard
 #Uncomment for running out of the repository scripts/sbtools directory
 #DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 #cd "${DIR}"
+
+# Don't run as root
+if [ $(id -u) -eq 0 ]; then
+  tput bold; echo "$(tput setaf 9)You do not need to run this script using sudo, it will handle sudo as required$(tput setaf 9)" ; tput sgr0
+  exit 1
+fi
 
 # Use colors, but only if connected to a terminal
 # and that terminal supports them.
@@ -61,39 +68,37 @@ git config rebase.autoStash true
 local ret=0
 
 # Update nhl-led-scoreboard
-printf "${BLUE}%s${RESET}\n" "Updating NHL LED Scoreboard"
+printf "${GREEN}%s${RESET}\n" "Seeing if we can update the NHL LED Scoreboard"
 last_commit=$(git rev-parse HEAD)
 if git pull --rebase --stat origin master; then
   # Check if it was really updated or not
   if [[ "$(git rev-parse HEAD)" = "$last_commit" ]]; then
     message="NHL LED Scoreboard is already at the latest version."
     ret=80 # non-zero exit code to indicate no changes pulled
-    printf "${BLUE}%s${RESET}\n" "$message"
-    exit $ret
   else
-    message="NHL LED Scoreboard has been updated!"
+    message="Hooray! NHL LED Scoreboard has been updated!"
 
     # Save the commit prior to updating
     git config nhl-led-scoreboard.lastVersion "$last_commit"
 
     # Display changelog with less if available, otherwise just print it to the terminal
     if [[ $ret -eq 0 ]]; then
-      "/home/pi/sbtools/changelog.sh" HEAD "$last_commit"
+      #"/home/pi/sbtools/changelog.sh" HEAD "$last_commit"
       # Uncomment line below if running from repository scripts/sbtools directory
-      # scripts/sbtools/changelog.sh HEAD "$last_commit"
-    fi
+      scripts/sbtools/changelog.sh HEAD "$last_commit"
+    #fi
 
     #Comment out if running from repositories scripts/sbtools directory
-    printf "${BLUE}%s \`${BOLD}%s${RESET}${BLUE}\`${RESET}\n" "You can see the changelog anytime with" "sb-changelog"
+    #printf "${BLUE}%s \`${BOLD}%s${RESET}${BLUE}\`${RESET}\n" "You can see the changelog anytime with" "sb-changelog"
    if [[ -a requirements.txt ]]; then
        #Check to see if the requirements.txt has changed, if so, run the pip3 install -r requirements.txt again
        if ! git diff -s --exit-code HEAD "$last_commit" requirements.txt; then
           printf "${GREEN}%s${RESET}\n" "New python library requirements for this version, installing now"
-          printf "${BLUE}%s${RESET}\n" "Activating scoreboard venv"
-          #Activate the venv
-          source /home/pi/nhlsb-venv/bin/activate
-          pip3 install -U -r requirements.txt
-          deactivate
+          if [ -n "$VIRTUAL_ENV" ]; then
+                pip3 install -U -r requirements.txt
+          else
+                sudo pip3 install -U -r requirements.txt
+          fi
        else
           printf "${YELLOW}%s${RESET}\n" "No new python libraries required to be installed."
        fi
@@ -105,25 +110,44 @@ if git pull --rebase --stat origin master; then
     if [[ -a apt-requirements ]]; then 
        if ! git diff -s --exit-code HEAD "$last_commit" apt-requirements; then
           printf "${GREEN}%s${RESET}\n" "New apt requirements for this version, installing now"
-          sudo /usr/local/bin/aptfile apt-requirements
-	  #Uncomment if running from repo scripts/sbtools, comment out above line
-          #sudo scripts/sbtools/aptfile apt-requirements
+          #sudo /usr/local/bin/aptfile apt-requirements
+	        #Uncomment if running from repo scripts/sbtools, comment out above line
+          sudo scripts/sbtools/aptfile apt-requirements
        else
           printf "${YELLOW}%s${RESET}\n" "No new apt required to be installed."
       fi
     else
           printf "${RED}%s${RESET}\n" "No apt-requirements found"
     fi
+
+    #Check to see if the nhl_setup has changed, if so, download the newest version
+    if [[ -a ../../nhl_setup ]]; then
+      printf "${GREEN}%s${RESET}\n" "Checking for new version of nhl_setup..."
+      LATEST_NHL_SETUP_VERSION=$(curl -s https://lastversion-api.getpagespeed.com/falkyre/nhl-setup?version)
+      CURRENT_NHL_SETUP_VERSION=$(../../nhl_setup -v | awk '{print $2}')
+      if [[ "$LATEST_NHL_SETUP_VERSION" != "$CURRENT_NHL_SETUP_VERSION" ]]; then
+        printf "${GREEN}%s${RESET}\n" "Newer version of nhl_setup found. Downloading..."
+        if [ "$ARCH" = "aarch64" ]; then
+            wget -q https://github.com/falkyre/nhl-setup/releases/latest/download/nhl_setup.64 -O ../../nhl_setup
+            chmod +x ../../nhl_setup
+            printf "${GREEN}%s${RESET}\n" "nhl_setup updated to version $LATEST_NHL_SETUP_VERSION"
+        elif [ "$ARCH" = "armv7l" ]; then
+            wget -q https://github.com/falkyre/nhl-setup/releases/latest/download/nhl_setup.32 -O ../../nhl_setup
+            chmod +x ../../nhl_setup
+            printf "${GREEN}%s${RESET}\n" "nhl_setup updated to version $LATEST_NHL_SETUP_VERSION"
+        else
+            printf "${RED}%s${RESET}\n" "Unsupported architecture for nhl_setup: $ARCH"
+        fi
+      else
+        printf "${YELLOW}%s${RESET}\n" "nhl_setup is already at the latest version."
+      fi
+    fi
+  fi
   fi
   # Update the status of the download so image user is not asked to upgrade on login again
   # comment the line below if running from the repo
-  /home/pi/sbtools/checkUpdate.sh > /home/pi/.nhlledportal/status
-  
-  #sudo zram-config sync
-  # Force reboot to sync update to SD card
-  #whiptail --title "Sync Update to SD Card" --msgbox "Pressing OK will reboot your pi and sync the update to the SD card" 20 60 2
-  #sudo reboot
-  message="NHL LED Scoreboard has been updated and synced to SD card!"
+  #/home/pi/sbtools/checkUpdate.sh > /home/pi/.nhlledportal/status
+  printf "${YELLOW}%s${RESET}\n" "$message"
 else
   ret=$?
   printf "${RED}%s${RESET}\n" 'There was an error updating. Try again later?'
@@ -135,6 +159,5 @@ case "$resetAutoStash" in
   *) git config rebase.autoStash "$resetAutoStash" ;;
 esac
 
-printf "${BLUE}%s${RESET}\n" "$message"
 # Exit with `1` if the update failed
 exit $ret
